#!/usr/bin/env bash
exec 200>/tmp/sunfire-kitty-lock
flock 200 || exit 1

#Wait a moment to prevent kitty from being overwhelmed and crashing
sleep 0.01

# 1. Tell Kitty to delete the graphics at this ID
kitty-helper delete_img $SUNFIRE_KITTY_IMAGE_ID 0
