#!/usr/bin/env bash
exec 200>/tmp/sunfire-kitty-lock
flock 200 || exit 1

#Wait a moment to prevent kitty from being overwhelmed and crashing
sleep 0.01

set -euo pipefail
IFS=$'\n\t'

MAX_PREVIEW_DIMENSION="1024x1024>"

THUMBNAIL_FPATH="$SUNFIRE_KITTY_TEMPDIR/thumbnail.png"
mime=$(file --mime-type -Lb "$1")

FILE_PATH="$1"
WIDTH="$2"
HEIGHT="$3"
POS_X="$4"
POS_Y="$5"

wipe_pane() {
    # 1. Tell Kitty to delete the graphics at this ID
    kitty-helper delete_img "$SUNFIRE_KITTY_IMAGE_ID" 1
}

trap cleanup INT HUP EXIT

wipe_pane

case "$mime" in
image/png|image/jpeg|image/bmp|image/svg+xml|image/webp)
    gm convert "$1" -resize "$MAX_PREVIEW_DIMENSION" "$THUMBNAIL_FPATH" 2>/dev/null || exit 0
    kitty-helper show "$THUMBNAIL_FPATH" "$SUNFIRE_KITTY_IMAGE_ID" 1 "$4" "$5" "$2" "$3"
    ;;
image/gif)
    gm convert "${1}[0]" -resize "$MAX_PREVIEW_DIMENSION" "$THUMBNAIL_FPATH" 2>/dev/null || exit 0
    kitty-helper show "$THUMBNAIL_FPATH" "$SUNFIRE_KITTY_IMAGE_ID" 1 "$4" "$5" "$2" "$3"
    ;;
application/pdf)
    gs -o "$THUMBNAIL_FPATH" -sDEVICE=pngalpha -dLastPage=1 "$1" >/dev/null 2>&1 || exit 0
    kitty-helper show "$THUMBNAIL_FPATH" "$SUNFIRE_KITTY_IMAGE_ID" 1 "$4" "$5" "$2" "$3"
    ;;
video/*)
    ffmpegthumbnailer -i "$1" -o "$THUMBNAIL_FPATH" -s 1024 >/dev/null 2>&1 || exit 0
    kitty-helper show "$THUMBNAIL_FPATH" "$SUNFIRE_KITTY_IMAGE_ID" 1 "$4" "$5" "$2" "$3"
    ;;
text/*|application/json)

    expand -t 4 "$FILE_PATH" | head -n "$HEIGHT" | awk \
        -v x=$((POS_X + 1)) \
        -v y=$((POS_Y + 1)) \
        -v w="$WIDTH" \
        '{
            # Truncate the line to the max width
            line = substr($0, 1, w)
            # Construct the "Move Cursor" + "Line Text" string
            # NR is the current line number (starts at 1)
            printf "\033[%d;%dH%s", y + (NR - 1), x, line
        }'
    ;;
*)
    msg="No preview available ($mime)"

    # Truncate message if it's too long
    if (( ${#msg} > WIDTH )); then
        msg="${msg:0:WIDTH}"
    fi

    # Output move command and text as a single string
    # ANSI format: \033[Line;ColumnH
    printf "\033[%d;%dH%s" $((POS_Y + 1)) $((POS_X + 1)) "$msg"
    ;;
esac

exit 0
